### ISSUE TITLE
Unlocking cosmic with fingerprint does not prompt for keyring password

### ISSUE THREAD

**Issue by NateWright** [lilyinstarlight/nixos-cosmic#220]
I am using cosmic on NixOS unstable. When I unlock with a password after forcing fingerprint auth to fail, then it successfully unlocks gnome-keyring. If I use my fingerprint to unlock, then it does not prompt to unlock gnome-keyring (like gnome would) and I cannot unlock it from seahorse. I am not sure if this is a nixos-cosmic issue or a cosmic one.

**Comment by NateWright** [comment]
Manually starting gnome-keyring has this error.
```
[nwright@nwright-framework:~]$ gnome-keyring-daemon --replace --foreground --components=secrets
discover_other_daemon: 0** Message: 11:35:05.914: Replacing daemon, using directory: /run/user/1001/keyring
GNOME_KEYRING_CONTROL=/run/user/1001/keyring

** (gnome-keyring-daemon:5017): WARNING **: 11:35:28.397: couldn't create system prompt: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.gnome.keyring.SystemPrompter exited with status 1
```

**Comment by lilyinstarlight** [comment]
Well I'd rather `start-cosmic` do this upstream, but I've pushed f929074895ac91f3d657e642a0d3d38dec682bfd to work around it in nixos-cosmic which fixes basically anything systemd- or dbus- activated (e.g. portals, gkr, etc)

Can you try again and see if that fixes it?

**Comment by lilyinstarlight** [comment]
Closing since it should be resolved. Feel free to reopen if you're still having issues!

**Comment by lilyinstarlight** [comment]
> Apologies for the churn here. I'm not sure where I messed up my testing (maybe logging out isn't enough?) but nonetheless rebooting my machine caused the the behavior to regress again, which shows that I was wrong about `XAUTHORITY`. Reverting my local workaround to again update the dbus environment with `--all` and rebooting still works. I'm not sure what variable it actually responsible, or if it's something else entirely. How can I best help with this?

I was very skeptical XAUTHORITY would matter. Can you share `env` from terminal and `systemctl --user show-environment`?

**Comment by NateWright** [comment]
This is still an issue on my Framework laptop. Any other information I can provide?

**Comment by NateWright** [comment]
@ChanceHarrison  Yes, unable to unlock after logging in with fingerprint and I get the same error.
